# 개발 환경 설정
## ✅ 데이터베이스 (MySQL 설정)
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/soyun_board
    username: soyun
    password: 6164
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

## ✅ JWT 설정
jwt:
  secret: "RYt5FUQwStWvHT0L0HpM2pq6I5V6L9DjIADUpGEeaqQ3zxHFvLkKrjMmyXNfdv+xWdKDj1XEsJwFHP/kG/aqtA=="
